### ISSUE TITLE
In the learning MFE, a link to the forum is displayed even when the forum is not enabled

### ISSUE THREAD

**Issue by regisb** [openedx/build-test-release-wg#108]
In the LMS, it used to be possible to remove the discussion forum entirely by unsetting the `ENABLE_DISCUSSION_SERVICE` feature flag: https://edx.readthedocs.io/projects/edx-platform-technical/en/latest/featuretoggles.html#featuretoggle-FEATURES['ENABLE_DISCUSSION_SERVICE']
Now, in the learning MFE, a link to the forum is always displayed:

![discussion](https://user-images.githubusercontent.com/44319/141726135-8d039576-9a6b-446a-9f28-c62df8eddfb7.png)

The link href is "/discussion/forum". Opening this link triggers a 500 with the following stacktrace:

```
lms_1                        | Traceback (most recent call last):                                                                                                                                                  
lms_1                        |   File "/openedx/edx-platform/./lms/djangoapps/courseware/views/views.py", line 655, in get                                                                                         
lms_1                        |     return super().get(request, course=course, page_context=page_context, **kwargs)                                                                                                 
lms_1                        |   File "/openedx/venv/lib/python3.8/site-packages/web_fragments/views.py", line 23, in get                                                                                          
lms_1                        |     fragment = self.render_to_fragment(request, **kwargs)                                                                                                                           
lms_1                        |   File "/openedx/edx-platform/./lms/djangoapps/courseware/views/views.py", line 809, in render_to_fragment                                                                          
lms_1                        |     return tab.render_to_fragment(request, course, **kwargs)                                                                                                                        
lms_1                        |   File "/openedx/edx-platform/common/lib/xmodule/xmodule/tabs.py", line 291, in render_to_fragment                                                                                  
lms_1                        |     return self.fragment_view.render_to_fragment(request, course_id=str(course.id), **kwargs)                                                                                       
lms_1                        |   File "/openedx/edx-platform/./lms/djangoapps/discussion/views.py", line 719, in render_to_fragment                                                                                
lms_1                        |     base_context = _create_base_discussion_view_context(request, course_key)                                                                                                        
lms_1                        |   File "/openedx/edx-platform/./lms/djangoapps/discussion/views.py", line 420, in _create_base_discussion_view_context                                                              
lms_1                        |     user_info = cc_user.to_dict()                                                                                                                                                   
lms_1                        |   File "/openedx/edx-platform/./openedx/core/djangoapps/django_comment_common/comment_client/models.py", line 62, in to_dict                                                        lms_1                        |     self.retrieve()                                                                                                                                                                 
lms_1                        |   File "/openedx/edx-platform/./openedx/core/djangoapps/django_comment_common/comment_client/models.py", line 67, in retrieve                                                       lms_1                        |     self._retrieve(*args, **kwargs)                                                                                                                                                 
lms_1                        |   File "/openedx/edx-platform/./openedx/core/djangoapps/django_comment_common/comment_client/user.py", line 152, in _retrieve                                                       lms_1                        |     response = utils.perform_request(                                                                                                                                               
lms_1                        |   File "/openedx/edx-platform/./openedx/core/djangoapps/django_comment_common/comment_client/utils.py", line 65, in perform_request                                                 lms_1                        |     response = requests.request(                                                                                                                                                    
lms_1                        |   File "/openedx/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request                                                                                             lms_1                        |     return session.request(method=method, url=url, **kwargs)                                                                                                                        
lms_1                        |   File "/openedx/venv/lib/python3.8/site-packages/requests/sessions.py", line 528, in request                                                                                       lms_1                        |     prep = self.prepare_request(req)                                                                                                                                                
lms_1                        |   File "/openedx/venv/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request                                                                               lms_1                        |     p.prepare(                                                                                                                                                                      
lms_1                        |   File "/openedx/venv/lib/python3.8/site-packages/requests/models.py", line 316, in prepare                                                                                         lms_1                        |     self.prepare_url(url, params)                                                                                                                                                   
lms_1                        |   File "/openedx/venv/lib/python3.8/site-packages/requests/models.py", line 390, in prepare_url                                                                                     lms_1                        |     raise MissingSchema(error)                                                                                                                                                      
lms_1                        | requests.exceptions.MissingSchema: Invalid URL '/api/v1/users/3': No schema supplied. Perhaps you meant http:///api/v1/users/3?  
```

When the ENABLE_DISCUSSION_SERVICE feature flag is disabled, I would expect that:
- [ ] the Discussion link not be displayed in the learning MFE.
- [ ] opening the /courses/<course_id>/discussion/forum url in the LMS should return a 404, and not trigger a 500 error

**Comment by regisb** [comment]
According to @davidjoy, during today's BTR WG meetup, this issue might be caused by the LMS backend, which might be returning some invalid urls.

**Comment by regisb** [comment]
Looks like I can't reproduce this anymore :sweat_smile: After investigation, it is this url which returns the menu items that are meant to be displayed in the learning MFE: api/courseware/course/<course-id>
The "Discussion" menu item is no longer returned by this API endpoint when the forum is disabled, so I'm going to close this issue. Let's re-open it if the issue occurs again in the future.

Sorry about the noise!

**Comment by ghassanmas** [comment]
Hey @regisb, 
For me when testing the fourm, the discussion tab didn't appear when it suppose to: i.e the **fourm is enabled** . Add to that when visiting the fourm (when I change the URL myself to _lms.com/courses/course-id/discussion/forum_ ),  I wasn't able to post a post, here is the output of the browser dev console: (a 404 was returned for the AJAX POST request):

`POST http://lms.com/courses/course-id/discussion/i4x-edx-eiorguegnru-course-foobarbaz/threads/create?ajax=1 404 (Not Found)
`

**Comment by ghassanmas** [comment]
[Update] when setting is or hard coding it to return `True`, the **disccsuion** tab appeard:

Ref: https://github.com/edx/edx-platform/blob/5e65be525a772bbdbbce99a56e2855daebfb56df/lms/djangoapps/discussion/django_comment_client/utils.py#L1067

**Comment by regisb** [comment]
@ghassanmas can you please check whether the maple branch of the tutor-forum plugin works for you? https://github.com/overhangio/tutor-forum/pull/3

**Comment by ghassanmas** [comment]
Yes I tested it localloy with my branch for maple , I meant to push it but got busy with other stuff. 

Anyway adding this feature `ENABLE_DISCUSSION_SERVICE` in the tutor-fourm plugin resolved both the tab issue and the AJAX failed request.

**Comment by regisb** [comment]
Ok then I'm closing this again.
