### ISSUE TITLE
default `ENABLED_*OVERRIDE*` settings values lack fully qualified module

### ISSUE THREAD

**Issue by pdpinch** [openedx/build-test-release-wg#112]
> There's a relatively small fix that we should upstream for Maple. The default values [here](https://github.com/edx/edx-platform/blob/open-release%2Fmaple.master/lms/djangoapps/courseware/field_overrides.py#L30-L31) are lacking the fully qualified module which results in the following traceback:

```
2021-11-22 11:37:40,490 ERROR 971 [lms.djangoapps.courseware.module_render] [user 5] [ip 76.127.137.77] module_render.py:340 - Error in get_module
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/module_render.py", line 327, in get_module
    return get_module_for_descriptor(user, request, descriptor, field_data_cache, usage_key.course_key,
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/module_render.py", line 417, in get_module_for_descriptor
    return get_module_for_descriptor_internal(
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/module_render.py", line 885, in get_module_for_descriptor_internal
    descriptor.bind_for_student(
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 708, in bind_for_student
    wrapped_field_data = wrapper(wrapped_field_data)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/field_overrides.py", line 163, in wrap
    cls.provider_classes = tuple(resolve_dotted(name) for name in settings.FIELD_OVERRIDE_PROVIDERS)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/field_overrides.py", line 163, in <genexpr>
    cls.provider_classes = tuple(resolve_dotted(name) for name in settings.FIELD_OVERRIDE_PROVIDERS)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/field_overrides.py", line 41, in resolve_dotted
    target = __import__(path)
ModuleNotFoundError: No module named 'courseware'
```

**Comment by pdpinch** [comment]
> This commit addresses the problem https://github.com/mitodl/edx-platform/tree/fix_override_provider_namespace

**Comment by arslanashraf7** [comment]
_Update:_

An upstream PR has been created for this https://github.com/edx/edx-platform/pull/29391
