### ISSUE TITLE
openedx-i18n needs to be upgraded to nutmeg

### ISSUE THREAD

**Issue by regisb** [openedx/build-test-release-wg#149]
The i18n strings from [openedx-i18n](https://github.com/openedx/openedx-i18n) need to be upgraded to Nutmeg in order to have up-to-date translation strings in the "openedx" Docker image.

Currently, we deploy the openedx Docker image in CD using outdated strings: https://github.com/overhangio/nutmeg-demo/blob/7a1be160a52d5ed82356c8d7bfba2beffe6649a4/.github/workflows/deploy.yml#L47

To mark this issue as resolved we need to:
1. Replace "open-release/maple.3" by "open-release/nutmeg.master" in this Dockerfile: https://github.com/openedx/openedx-i18n/tree/master/docker/Dockerfile
2. Run `make all`.
3. Commit the changes and push them to a "open-release/nutmeg.master" branch.

Currently, step 2 is failing:

```
$ make all
...
docker run --rm -it -v /home/regis/projets/overhang/repos/edx/openedx-i18n/edx-platform/locale/:/openedx/edx-platform/conf/locale/ -v /home/regis/projets/overhang/repos/edx/openedx-i18n/transifexrc:/openedx/.transifexrc openedx-i18n i18n_tool transifex --config=conf/locale/config-extra.yaml pull
Pulling conf/locale/config.yaml:locales from Transifex...
tx ERROR: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/openedx/venv/bin/i18n_tool", line 8, in <module>
    sys.exit(main())
  File "/openedx/venv/lib/python3.8/site-packages/i18n/main.py", line 60, in main
    return module.main()
  File "/openedx/venv/lib/python3.8/site-packages/i18n/__init__.py", line 50, in __call__
    return self.run(args)
  File "/openedx/venv/lib/python3.8/site-packages/i18n/transifex.py", line 160, in run
    pull(self.configuration, *args.arg)
  File "/openedx/venv/lib/python3.8/site-packages/i18n/transifex.py", line 62, in pull
    execute(cmd)
  File "/openedx/venv/lib/python3.8/site-packages/i18n/execute.py", line 21, in execute
    sp.check_call(command, cwd=working_directory, stderr=stderr, shell=True)
  File "/opt/pyenv/versions/3.8.12/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'tx pull -f --mode=reviewed --minimum-perc=3 -l ca' returned non-zero exit status 1.
make: *** [Makefile:26: download] Error 1
```

It seems like the `tx` client is crashing, with very little in terms of information:

```
$ docker run --rm -it -v $(pwd)/edx-platform/locale/:/openedx/edx-platform/conf/locale/ -v $(pwd)transifexrc:/openedx/.transifexrc openedx-i18n bash
$ tx pull -f --mode=reviewed --minimum-perc=3 -l ca
tx ERROR: not enough values to unpack (expected 2, got 1)
```

I have no idea what may be causing this issue.

**Comment by regisb** [comment]
This is now resolved: https://github.com/openedx/openedx-i18n/compare/master...open-release/nutmeg.master
