### ISSUE TITLE
Error importing BAR_TYPES with new pip 22.1 release

### ISSUE THREAD

**Issue by cmltaWt0** [openedx/build-test-release-wg#178]
Description
------------
pip-tools fails with latest pip==22.1 version.
The failure details are in the issue https://github.com/jazzband/pip-tools/issues/1617

Proposed fix
-------------
It can be fixed by pining the pip version <22.1.
But also it looks like the issue can be fixed by upgrading pip-tools to the [latest](https://pypi.org/project/pip-tools/6.6.1/) version.
According to the [issue](https://github.com/jazzband/pip-tools/issues/1617) discussion -  `Fix released as part of pip-tools v6.6.1.`

I did the fix for `enterprice-catalog` and `license-maneger`.

## How to reproduce

```
> pip --version
pip 22.1 
> pip install -U pip-tools==6.4.0
> pip-compile --version                                                                                                                                                 cmltawt0/fix/piptools
Traceback (most recent call last):
  File "/code/openedx/license-manager/.venv/bin/pip-compile", line 5, in <module>
    from piptools.scripts.compile import cli
  File "/code/openedx/license-manager/.venv/lib/python3.8/site-packages/piptools/scripts/compile.py", line 21, in <module>
    from ..repositories import LocalRequirementsRepository, PyPIRepository
  File "/code/openedx/license-manager/.venv/lib/python3.8/site-packages/piptools/repositories/__init__.py", line 1, in <module>
    from .local import LocalRequirementsRepository
  File "/code/openedx/license-manager/.venv/lib/python3.8/site-packages/piptools/repositories/local.py", line 14, in <module>
    from .pypi import PyPIRepository
  File "/code/openedx/license-manager/.venv/lib/python3.8/site-packages/piptools/repositories/pypi.py", line 22, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
ImportError: cannot import name 'BAR_TYPES' from 'pip._internal.cli.progress_bars' 
```

## How to check fix

```
> make production-requirements                                                                                                                                          
pip install -r requirements/pip-tools.txt
............
Requirement already satisfied: pip>=21.2 in ./.venv/lib/python3.8/site-packages (from pip-tools==6.6.1->-r requirements/pip-tools.txt (line 13)) (22.1)
Requirement already satisfied: setuptools in ./.venv/lib/python3.8/site-packages (from pip-tools==6.6.1->-r requirements/pip-tools.txt (line 13)) (62.0.0)
Installing collected packages: pip-tools
  Attempting uninstall: pip-tools
    Found existing installation: pip-tools 6.4.0
    Uninstalling pip-tools-6.4.0:
      Successfully uninstalled pip-tools-6.4.0
Successfully installed pip-tools-6.6.1
> pip-compile --version                                                                                                                                                 
pip-compile, version 6.6.1
```

**Comment by cmltaWt0** [comment]
PRs:
- https://github.com/openedx/enterprise-catalog/pull/453
- https://github.com/openedx/enterprise-catalog/pull/454
- https://github.com/openedx/license-manager/pull/427
- https://github.com/openedx/license-manager/pull/428


P.S.
I didn't get the reason of Action fail for enterprise Nutmeg though:
```
cd enterprise_catalog && i18n_tool changed
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>
Source translations are out-of-date! Please update them.
make: *** [detect_changed_source_translations] Error 1
Makefile:139: recipe for target 'detect_changed_source_translations' failed
Error: Process completed with exit code 2.
```
