### ISSUE TITLE
Lilac installation failure: pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by nedbat** [openedx/build-test-release-wg#63]
I'm getting a failure in CI of the native installation (lilac) at
```
TASK [edxapp : migrate]
```
with decoded error:
```
== module_stderr ===========================
/root/.ansible/tmp/ansible-tmp-1620207334.0064898-65933-58367663946137/AnsiballZ_mongodb_rs_status:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1620207334.0064898-65933-58367663946137/AnsiballZ_mongodb_rs_status", line 114, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1620207334.0064898-65933-58367663946137/AnsiballZ_mongodb_rs_status", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1620207334.0064898-65933-58367663946137/AnsiballZ_mongodb_rs_status", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 604, in _exec
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/ansible_mongodb_rs_status_payload_9wawaefo/__main__.py", line 133, in <module>
  File "/tmp/ansible_mongodb_rs_status_payload_9wawaefo/__main__.py", line 115, in main
  File "/usr/local/lib/python3.8/dist-packages/pymongo/database.py", line 529, in command
    with client._socket_for_reads(read_preference) as (sock_info, slave_ok):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/dist-packages/pymongo/mongo_client.py", line 982, in _socket_for_reads
    server = topology.select_server(read_preference)
  File "/usr/local/lib/python3.8/dist-packages/pymongo/topology.py", line 222, in select_server
    return random.choice(self.select_servers(selector,
  File "/usr/local/lib/python3.8/dist-packages/pymongo/topology.py", line 182, in select_servers
    server_descriptions = self._select_servers_loop(
  File "/usr/local/lib/python3.8/dist-packages/pymongo/topology.py", line 198, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused
```

**Comment by nedbat** [comment]
Slack discussion here: https://openedx.slack.com/archives/C01AGTSB1LL/p1620212936128700

**Comment by nedbat** [comment]
Koa.master now fails in the same way.  @sambapete's theory about Django 2.2.21 being the problem seems right.  I wrote this Django issue: https://code.djangoproject.com/ticket/32725

**Comment by nedbat** [comment]
There's already an active discussion about it: https://code.djangoproject.com/ticket/32718

**Comment by nedbat** [comment]
From the Django ticket (https://code.djangoproject.com/ticket/32718#comment:29):

 Thanks y'all for various test projects and detailed reports of encountered issue with saving FileFields.

> After some discussions, we decided to prepare a patch for ​FileField.generate_filename() that should solve most of these issues. Please see the following points.
> 
>     If filename passed to the FileField.generate_filename() is an absolute path, it will be converted to the os.path.basename(filename).
>     Validate filename returned by FileField.upload_to() not a filename passed to the FileField.generate_filename() (upload_to() may completely ignored passed filename).
>     Allow relative paths (without dot segments) in the generated filename. 
> 
> We're going to prepare a patch in the next few days.

**Comment by nedbat** [comment]
Questions to consider: 
- why didn't a failed migration fail the installation?
- why did a failed migration cause a strange pymongo error?

**Comment by regisb** [comment]
> why didn't a failed migration fail the installation?

I'm not sure what you mean: the failed migration did cause the installation to fail, didn't it? For instance, in the case of this particular build, the installation stopped after a failure of the "edxapp : migrate" task: https://git.overhang.io/community/openedx-configuration-ci/-/jobs/3535

> why did a failed migration cause a strange pymongo error?

I think I understand what is happening here. The pymongo error was _not_ triggered by the failed migration. It is simply some error log that happened earlier and was only reported by Ansible at the very end because Ansible collects all stderr output before the final reporting. The mongodb error comes from the custom [`mongodb_rs_status`](https://github.com/edx/configuration/blob/master/playbooks/library/mongodb_rs_status) module that is supposed to check on the status of the MongoDb replicaset. 

This task is run, for instance, as part of the mongo_3_6 role: https://github.com/edx/configuration/blob/f95d6e1ba52ff851dfabf7a4d6b22d517c848645/playbooks/roles/mongo_3_6/tasks/main.yml#L115 It is run with `ignore_errors: true`, which explains why the error did not stop the Ansible run.

The reason why it fails is probably that the configuration repo depends on a version of pymongo that is not recent enough (3.9.0 instead of 4.0.0): https://github.com/edx/configuration/blob/f95d6e1ba52ff851dfabf7a4d6b22d517c848645/requirements/base.in#L18

**Comment by nedbat** [comment]
My two questions boiled down to: why did the ansible error summary find the wrong error to summarize?  I've got a simple PR to fix that: https://github.com/edx/configuration/pull/6401   Anyone got a thumb-up for it?
